spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.88.246:3306/springboot_cache
    username: root
    password: 123456
    dbcp2:
          min-idle: 5         #最小连接数
          initial-size: 5    #初始化连接数
          max-total: 10      #最大连接数
          max-wait-millis: 200  #等待连接最长的超时时间